### ISSUE TITLE
 error: window is not defined

### ISSUE THREAD

**Issue by leeduckgo** [leeduckgo/web3-blog-ts#6]
```
yarn build
```

 WebpackError: ReferenceError: window is not defined.

参考解决方案：

> https://blog.greenroots.info/gatsby-the-window-is-not-defined-error-what-and-how-to-fix-it
>
> https://github.com/gatsbyjs/gatsby/issues/309

**Comment by leeduckgo** [comment]
¥300

**Comment by Zombieliu** [comment]
#7
